{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turbostat-exporter.fullname" . }}
  labels:
    {{- include "turbostat-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "basicAuth.password is required when basicAuth.enabled is true and basicAuth.existingSecret is not set" .Values.basicAuth.password | quote }}
{{- end -}}
