name: Go

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: go.sum
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o turbostat-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
      # - name: Archive binaries
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: turbostat-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
      #     path: turbostat-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            turbostat-exporter-*
